# Generated by Django 2.1 on 2018-10-13 01:11

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=64)),
                ('p_content', DjangoUeditor.models.UEditorField()),
                ('p_read_count', models.IntegerField(default=0)),
                ('p_datetime', models.DateTimeField(auto_now=True)),
                ('p_language', models.CharField(max_length=32)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
