# Generated by Django 2.1.2 on 2018-10-08 14:14

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=64)),
                ('pinfo', DjangoUeditor.models.UEditorField()),
                ('pread_count', models.IntegerField(default=0)),
                ('pdatetime', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
